### ISSUE TITLE
gcloud docker cannot push to gcr.io anymore?

### ISSUE THREAD

**Issue by krzyzacy** [GoogleCloudPlatform/docker-credential-gcr#21]
I already configured
```
~/work/src/k8s.io/test-infra/images/kubekins-e2e$ docker-credential-gcr configure-docker --overwrite
~/.docker/config.json successfully configured
Any previously stored credentials have been overwritten.
~/work/src/k8s.io/test-infra/images/kubekins-e2e$ docker-credential-gcr gcr-login
```

```
gcloud docker -- push gcr.io/k8s-testimages/kubekins-e2e:v20180119-64c9c32f7-master
ERROR: Docker CLI operation failed:

Error saving credentials: error storing credentials - err: exit status 1, out: `docker-credential-gcr/helper: this operation is unsupported for GCR, please see docker-credential-gcr documentation for supported login methods. 'gcloud docker' is unnecessary when using docker-credential-gcr, use 'docker' instead.`

ERROR: (gcloud.docker) Docker login failed.
make: *** [push] Error 1
```

while
```
docker push gcr.io/k8s-testimages/kubekins-e2e:v20180119-64c9c32f7-master
```
works perfectly fine

**Comment by dekkagaijin** [comment]
`gcloud` is unnecessary if you've configured Docker to use the cred helper via `configure-docker` and logged in using `gcr-login`. Using `docker`, alone, is correct :)

**Comment by krzyzacy** [comment]
@dekkagaijin in our build environment it does not have `docker-credential-gcr` configured, while I have it locally - I would expect it will work in both cases

plus it was working previously, seems this is a fairly recent change from gcloud side?

**Comment by dekkagaijin** [comment]
If the goal is to use `gcloud docker`, you should disassociate `docker-credential-gcr` as the credential helper for GCR's repositories. This can be done by removing all `credsStore` and `credHelpers` entries from the docker config (`~/.docker/config.json`). 

> seems this is a fairly recent change from gcloud side?

`gcloud docker` was a hack that was necessary to authenticate GCR's users before the advent of Docker credential helpers. There is no one way to authenticate all versions of the Docker client in all OSs/environments that we wish to support, which has lead to an increasing number of hacks added on over the years. A few releases ago, we encountered an issue with some newer versions/environments which was fixed by eliminating the usability hack which made `gcloud docker` a no-op when it detected that `docker-credential-gcr` was configured.

We believe that an error is the correct decision in this case because it eliminates a major source of confusion and debugging headaches which arise when users are unable to determine how their requests to GCR is being authenticated and where the `access_token` originates.

If you use `gcloud` in both your dev and build environments, one option would be to use the `gcloud`-specific credential helper, `docker-credential-gcloud`. `docker` can be configured to use it using the following command: [`gcloud beta auth configure-docker`](https://cloud.google.com/sdk/gcloud/reference/beta/auth/configure-docker), which will then allow you to use naked `docker push gcr.io...` which will automatically be authenticated by the currently active `gcloud` account's credentials.

**Comment by krzyzacy** [comment]
thanks for the explanation @dekkagaijin!

**Comment by dekkagaijin** [comment]
Happy to help :)

**Comment by krzyzacy** [comment]
@dekkagaijin one more follow up question now:

so when we try to run in CI, bare `docker push` to gcr.io fails now because of credentials, so we try to run `gcloud beta auth configure-docker` before doing the push, however we get:
```
I0215 01:37:26.182] gcloud beta auth configure-docker
W0215 01:37:26.957] ERROR: (gcloud.beta.auth.configure-docker) Error writing Docker configuration to disk: [Errno 2] No such file or directory: '/root/.docker/tmptiqGEe'
W0215 01:37:27.002] make: *** [push] Error 1
```
any clue what might cause this?

cc @nikhiljindal @bentheelder

**Comment by BenTheElder** [comment]
> any clue what might cause this?

This is almost definitely related to the way /root is mounted in that job.

**Comment by dekkagaijin** [comment]
`gcloud auth configure-docker` is completely independent from `docker-credential-gcr`, unfortunately. In order to atomically re-write the docker config, `gcloud` will write contents to a temporary file in `~/.docker/` and then rename it to `~/.docker/config.json`.  It looks like that temp file ceases to exist at some point between creation and writing/renaming.

**Comment by ixdy** [comment]
`gcloud auth configure-docker` should probably check to make sure `~/.docker/` exists first, creating it if necessary. I ran into the same issue trying to run it on my own machine:
```console
$ gcloud beta auth configure-docker
The following settings will be added to your Docker config file
located at [/home/jgrafton/.docker/config.json]:
 {                                         
  "credHelpers": {                         
    "gcr.io": "gcloud",                    
    "us.gcr.io": "gcloud",                 
    "eu.gcr.io": "gcloud",                 
    "asia.gcr.io": "gcloud",               
    "l.gcr.io": "gcloud",                  
    "launcher.gcr.io": "gcloud",           
    "us-mirror.gcr.io": "gcloud",          
    "eu-mirror.gcr.io": "gcloud",          
    "asia-mirror.gcr.io": "gcloud",        
    "mirror.gcr.io": "gcloud",             
    "k8s.gcr.io": "gcloud"                 
  }                                        
}                                          
                                           
Do you want to continue (Y/n)?  y          
                                           
ERROR: (gcloud.beta.auth.configure-docker) Error writing Docker configuration to disk: [Errno 2] No such file or directory: '/home/jgrafton/.docker/tmpxVqCJR'
```

I'm guessing this is probably the wrong repo to report this issue, though.

**Comment by ixdy** [comment]
for any Googlers following along, I opened an internal bug for the issue I described (id 74010053).

**Comment by praveeny1986** [comment]
Yeah I am facing the same issue. Cannot push images to gcr.

**Comment by dekkagaijin** [comment]
@praveeny1986 What's the exact error?

**Comment by praveeny1986** [comment]
gcloud beta auth configure-docker
The following settings will be added to your Docker config file
located at [/home/praveen/.docker/config.json]:
 {
  "credHelpers": {
    "gcr.io": "gcloud",
    "us.gcr.io": "gcloud",
    "eu.gcr.io": "gcloud",
    "asia.gcr.io": "gcloud",
    "staging-k8s.gcr.io": "gcloud",
    "k8s.gcr.io": "gcloud"
  }
}

Do you want to continue (Y/n)?

ERROR: (gcloud.beta.auth.configure-docker) Error writing Docker configuration to disk: [Errno 2] No such file or directory: '/home/praveen/.docker/tmp3WUHdu'

**Comment by praveeny1986** [comment]
@dekkagaijin ,
Google Cloud SDK 190.0.0
alpha 2018.02.16
beta 2018.02.16
bq 2.0.29
core 2018.02.16
gsutil 4.28

Ok let me update and try.
Thanks

**Comment by praveeny1986** [comment]
@dekkagaijin ,
Thanks it works now after updating.

**Comment by sebgoa** [comment]
I have a similar error. I did `gcloud auth configure-docker` the config.json got written.

But now when I push I see `denied: Token exchange failed for project` telling me that the API is not enabled in gcloud. BUT the API is indeed enabled in gcloud.

so I am at a loss

```
 $ docker version
Client:
 Version:      18.05.0-ce
 API version:  1.37
 Go version:   go1.9.5
 Git commit:   f150324
 Built:        Wed May  9 22:12:05 2018
 OS/Arch:      darwin/amd64
 Experimental: true
 Orchestrator: kubernetes

Server:
 Engine:
  Version:      18.05.0-ce
  API version:  1.37 (minimum version 1.12)
  Go version:   go1.10.1
  Git commit:   f150324
  Built:        Wed May  9 22:20:16 2018
  OS/Arch:      linux/amd64
  Experimental: true
 Kubernetes:
  Version:     Unknown
  StackAPI:                   Unknown
sebgoa@foobar bitnami $ kubectl version
Client Version: version.Info{Major:"1", Minor:"9", GitVersion:"v1.9.7", GitCommit:"dd5e1a2978fd0b97d9b78e1564398aeea7e7fe92", GitTreeState:"clean", BuildDate:"2018-04-19T00:05:56Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"9", GitVersion:"v1.9.6", GitCommit:"9f8ebd171479bec0ada837d7ee641dec2f8c6dd1", GitTreeState:"clean", BuildDate:"2018-03-21T15:13:31Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}

 $ gcloud --version
Google Cloud SDK 204.0.0
alpha 2017.09.15
beta 2017.09.15
bq 2.0.34
core 2018.06.04
docker-credential-gcr 
gcloud 
gsutil 4.31
kubectl 
```

**Comment by dekkagaijin** [comment]
@sebgoa
Please contact gcr-contact (at) google.com with the exact command being executed, and the exact error being seen.

**Comment by sebgoa** [comment]
well, never mind, user error :) I was trying to push to the wrong project ID.

my bad.
