### ISSUE TITLE
Unable to determine docker version error

### ISSUE THREAD

**Issue by dubwoc** [GoogleCloudPlatform/docker-credential-gcr#6]
~> docker-credential-gcr configure-docker
ERROR: Unable to determine Docker version: strconv.ParseInt: parsing "3'\n": invalid syntax

~> docker version
Client:
 Version:      1.12.3
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   6b644ec
 Built:        Wed Oct 26 21:39:14 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.12.3
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   6b644ec
 Built:        Wed Oct 26 21:39:14 2016
 OS/Arch:      linux/amd64

**Comment by dubwoc** [comment]
~> docker-credential-gcr version
Google Container Registry Docker credential helper 1.3.1

**Comment by KingEmet** [comment]
Thanks for reporting! There was an issue with the version parsing code which resulted in that error for some users, and has been fixed in 1.3.2, which will be included in the next gcloud release.

**Comment by convoy-team** [comment]
Your attempt to create an issue via email has failed.

Reason:
  User did not have permission to make an update in component '166824'

For information on how to use Buganizer's email interface please visit  
http://wiki.corp.google.com/twiki/bin/view/Main/BuganizerHelpEmailAccessToBuganizer.

Thanks!

Buganizer

Original body:

@KingEmet is there a way to use the 1.3.2 version now? I am getting the  
same error

-- 
You are receiving this because you are subscribed to this thread.
Reply to this email directly or view it on GitHub:
https://github.com/GoogleCloudPlatform/docker-credential-gcr/issues/6#issuecomment-273403631

-- 
You received this message because you are subscribed to the Google  
Groups "container registry contact" group.
To unsubscribe from this group and stop receiving emails from it, send an  
email to gcr-contact+unsubscribe@google.com.
To post to this group, send email to gcr-contact@google.com.
To view this discussion on the web visit  
https://groups.google.com/a/google.com/d/msgid/gcr-contact/GoogleCloudPlatform/docker-credential-gcr/issues/6/273403631%40github.com.

**Comment by KingEmet** [comment]
@dantei Yup, you can download a compiled binary for your appropriate platform here: https://github.com/GoogleCloudPlatform/docker-credential-gcr/releases/tag/v1.3.2

**Comment by convoy-team** [comment]
Your attempt to create an issue via email has failed.

Reason:
  User did not have permission to make an update in component '166824'

For information on how to use Buganizer's email interface please visit  
http://wiki.corp.google.com/twiki/bin/view/Main/BuganizerHelpEmailAccessToBuganizer.

Thanks!

Buganizer

Original body:

@dantei Yup, you can download a compiled binary for your appropriate  
platform here:  
https://github.com/GoogleCloudPlatform/docker-credential-gcr/releases/tag/v1.3.2

-- 
You are receiving this because you commented.
Reply to this email directly or view it on GitHub:
https://github.com/GoogleCloudPlatform/docker-credential-gcr/issues/6#issuecomment-273536147

-- 
You received this message because you are subscribed to the Google  
Groups "container registry contact" group.
To unsubscribe from this group and stop receiving emails from it, send an  
email to gcr-contact+unsubscribe@google.com.
To post to this group, send email to gcr-contact@google.com.
To view this discussion on the web visit  
https://groups.google.com/a/google.com/d/msgid/gcr-contact/GoogleCloudPlatform/docker-credential-gcr/issues/6/273536147%40github.com.

**Comment by KingEmet** [comment]
@dantei gcloud sdk v140 is out as of now

**Comment by convoy-team** [comment]
Your attempt to create an issue via email has failed.

Reason:
  User did not have permission to make an update in component '166824'

For information on how to use Buganizer's email interface please visit  
http://wiki.corp.google.com/twiki/bin/view/Main/BuganizerHelpEmailAccessToBuganizer.

Thanks!

Buganizer

Original body:

@dantei gcloud sdk v140 is out as of now

-- 
You are receiving this because you commented.
Reply to this email directly or view it on GitHub:
https://github.com/GoogleCloudPlatform/docker-credential-gcr/issues/6#issuecomment-273541721

-- 
You received this message because you are subscribed to the Google  
Groups "container registry contact" group.
To unsubscribe from this group and stop receiving emails from it, send an  
email to gcr-contact+unsubscribe@google.com.
To post to this group, send email to gcr-contact@google.com.
To view this discussion on the web visit  
https://groups.google.com/a/google.com/d/msgid/gcr-contact/GoogleCloudPlatform/docker-credential-gcr/issues/6/273541721%40github.com.
