### ISSUE TITLE
configure-docker doesn't work with new docker version scheme

### ISSUE THREAD

**Issue by arthurk** [GoogleCloudPlatform/docker-credential-gcr#7]
Docker switched to a new version scheme and it seems that it breaks the configure-docker 

```
$ docker-credential-gcr configure-docker
ERROR: Docker client version 1.10+ required

$ docker --version
Docker version 17.03.0-ce, build 60ccb22
```

**Comment by convoy-team** [comment]
Your attempt to create an issue via email has failed.

Reason:
  User did not have permission to make an update in component '166824'

For information on how to use Buganizer's email interface please visit  
http://wiki.corp.google.com/twiki/bin/view/Main/BuganizerHelpEmailAccessToBuganizer.

Thanks!

Buganizer

Original body:

Docker switched to a new version scheme and it seems that it breaks the  
configure-docker

```
$ docker-credential-gcr configure-docker
ERROR: Docker client version 1.10+ required

$ docker --version
Docker version 17.03.0-ce, build 60ccb22
```

-- 
You are receiving this because you are subscribed to this thread.
Reply to this email directly or view it on GitHub:
https://github.com/GoogleCloudPlatform/docker-credential-gcr/issues/7

-- 
You received this message because you are subscribed to the Google  
Groups "container registry contact" group.
To unsubscribe from this group and stop receiving emails from it, send an  
email to gcr-contact+unsubscribe@google.com.
To post to this group, send email to gcr-contact@google.com.
To view this discussion on the web visit  
https://groups.google.com/a/google.com/d/msgid/gcr-contact/GoogleCloudPlatform/docker-credential-gcr/issues/7%40github.com.

**Comment by KingEmet** [comment]
Was this with the lastest version of docker-credential-gcr (v1.3.4)?

**Comment by convoy-team** [comment]
Your attempt to create an issue via email has failed.

Reason:
  User did not have permission to make an update in component '166824'

For information on how to use Buganizer's email interface please visit  
http://wiki.corp.google.com/twiki/bin/view/Main/BuganizerHelpEmailAccessToBuganizer.

Thanks!

Buganizer

Original body:

Was this with the lastest version of docker-credential-gcr (v1.3.4)?

-- 
You are receiving this because you commented.
Reply to this email directly or view it on GitHub:
https://github.com/GoogleCloudPlatform/docker-credential-gcr/issues/7#issuecomment-285087918

-- 
You received this message because you are subscribed to the Google  
Groups "container registry contact" group.
To unsubscribe from this group and stop receiving emails from it, send an  
email to gcr-contact+unsubscribe@google.com.
To post to this group, send email to gcr-contact@google.com.
To view this discussion on the web visit  
https://groups.google.com/a/google.com/d/msgid/gcr-contact/GoogleCloudPlatform/docker-credential-gcr/issues/7/285087918%40github.com.

**Comment by arthurk** [comment]
This was with 1.3.2 (installed via gcloud components). I will test it with the latest version

**Comment by convoy-team** [comment]
Your attempt to create an issue via email has failed.

Reason:
  User did not have permission to make an update in component '166824'

For information on how to use Buganizer's email interface please visit  
http://wiki.corp.google.com/twiki/bin/view/Main/BuganizerHelpEmailAccessToBuganizer.

Thanks!

Buganizer

Original body:

This was with 1.3.2 (installed via gcloud components). I will test it with  
the latest version

-- 
You are receiving this because you commented.
Reply to this email directly or view it on GitHub:
https://github.com/GoogleCloudPlatform/docker-credential-gcr/issues/7#issuecomment-285090924

-- 
You received this message because you are subscribed to the Google  
Groups "container registry contact" group.
To unsubscribe from this group and stop receiving emails from it, send an  
email to gcr-contact+unsubscribe@google.com.
To post to this group, send email to gcr-contact@google.com.
To view this discussion on the web visit  
https://groups.google.com/a/google.com/d/msgid/gcr-contact/GoogleCloudPlatform/docker-credential-gcr/issues/7/285090924%40github.com.

**Comment by KingEmet** [comment]
Cool beans, gcloud's fix should drop next Wednesday (2015-03-15)
